
spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://localhost:3306/demo
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:

mybatis:
  type-aliases-package: com.dream9.dao.model
  mapper-locations: classpath:mapper/*.xml


mapper:
    mappers:
        - com.dream9.utils.MyMapper
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
#logging:
#  level:
#    org.springframework.web: error
#    com.dream9m9: info





